name: AppleMLXTutorials
options:
  bundleIdPrefix: dev.hyodot
  deploymentTarget:
    macOS: "14.0"
    iOS: "17.0"
  xcodeVersion: "16.0"

settings:
  base:
    SWIFT_VERSION: "5.10"
    ENABLE_USER_SCRIPT_SANDBOXING: false

packages:
  mlx-swift:
    url: https://github.com/ml-explore/mlx-swift
    from: 0.21.2
  mlx-swift-lm:
    url: https://github.com/ml-explore/mlx-swift-lm
    branch: main
  mlx-swift-examples:
    url: https://github.com/ml-explore/mlx-swift-examples
    branch: main

targets:
  AppleMLXTutorials:
    type: application
    platform: macOS
    sources:
      - AppleMLXTutorials
    dependencies:
      - package: mlx-swift
        product: MLX
      - package: mlx-swift
        product: MLXNN
      - package: mlx-swift
        product: MLXOptimizers
      - package: mlx-swift
        product: MLXRandom
      - package: mlx-swift-lm
        product: MLXLLM
      - package: mlx-swift-lm
        product: MLXLMCommon
      - package: mlx-swift-lm
        product: MLXVLM
      - package: mlx-swift-examples
        product: StableDiffusion
    entitlements:
      path: AppleMLXTutorials/AppleMLXTutorials.entitlements
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.hyodot.AppleMLXTutorials
        PRODUCT_NAME: AppleMLXTutorials
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.developer-tools
        INFOPLIST_KEY_CFBundleDisplayName: Apple MLX Tutorials
        GENERATE_INFOPLIST_FILE: YES
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        CODE_SIGN_ENTITLEMENTS: AppleMLXTutorials/AppleMLXTutorials.entitlements
      configs:
        Debug:
          CODE_SIGN_STYLE: Automatic
          CODE_SIGN_IDENTITY: "-"
        Release:
          CODE_SIGN_STYLE: Manual
          CODE_SIGN_IDENTITY: "Developer ID Application"
          DEVELOPMENT_TEAM: PRDQGB267K
          ENABLE_HARDENED_RUNTIME: YES
          CODE_SIGN_INJECT_BASE_ENTITLEMENTS: NO
          OTHER_CODE_SIGN_FLAGS: "--timestamp"
